# Generated by Django 4.2.7 on 2025-06-28 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='numero_de_telephone',
            new_name='phoneNumber',
        ),
    ]
