# Generated by Django 4.2.7 on 2025-06-22 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, help_text="Identifiant UUID de l'utilisateur externe")),
                ('message', models.CharField(help_text='Contenu brut du message de la transaction', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de réception')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('user_id', 'message'), name='unique_user_message_transaction'),
        ),
    ]
