# Generated by Django 4.2.7 on 2025-06-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_message', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('message', models.TextField()),
                ('category', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.FloatField(default=0)),
                ('fee', models.FloatField(default=0)),
                ('amount_total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaction traitée',
                'verbose_name_plural': 'Transactions traitées',
                'ordering': ['-created_at'],
            },
        ),
    ]
