# Generated by Django 4.2.7 on 2025-06-27 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('processed_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedtransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
