# Generated by Django 4.2.7 on 2025-06-28 07:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processed_messages', '0002_alter_processedtransaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant principal en FCFA', max_digits=15),
        ),
        migrations.AlterField(
            model_name='processedtransaction',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant total (principal + frais) en FCFA', max_digits=15),
        ),
        migrations.AlterField(
            model_name='processedtransaction',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frais en FCFA', max_digits=15),
        ),
    ]
